// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t USR_SENSOR_UPDATE;
void switch_event_cb(lv_event_t *event);
void common_sensor_event_cb(lv_event_t *event);
void light_sensor_event_cb(lv_event_t *event);
void light_cfg_entrence(lv_event_t *event);
void light_cfg_out(lv_event_t *event);
void light_color_update(lv_event_t *event);
void data_input_event(lv_event_t *e);
void ta_event_cb(lv_event_t *e);
void temp_analysis_event(lv_event_t *e);
//void void_cb(lv_event_t *event);
#ifdef __cplusplus
}
#endif

#endif
